version: '3.7'

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: turnip-api
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:password@postgres:5432/turnip-api
      BOT_TOKEN: "${BOT_TOKEN}"
